name: Monitor Phidata Repository

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  monitor:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Get latest commit
        id: latest
        uses: actions/github-script@v6
        with:
          script: |
            const { data: commits } = await github.rest.repos.listCommits({
              owner: 'phidatahq',
              repo: 'phidata',
              per_page: 1
            });
            
            // Get last commit details
            const latestCommit = commits[0];
            const sha = latestCommit.sha;
            const message = latestCommit.commit.message;
            const author = latestCommit.commit.author.name;
            const date = latestCommit.commit.author.date;
            
            // Get changed files
            const { data: commit } = await github.rest.repos.getCommit({
              owner: 'phidatahq',
              repo: 'phidata',
              ref: sha
            });
            
            const files = commit.files.map(file => ({
              name: file.filename,
              status: file.status,
              additions: file.additions,
              deletions: file.deletions
            }));
            
            core.setOutput('sha', sha);
            core.setOutput('message', message);
            core.setOutput('author', author);
            core.setOutput('date', date);
            core.setOutput('files', JSON.stringify(files));
            core.setOutput('changed', 'true');

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🔄 Phidata Repository Update Detected"
          to: alexanddanik@gmail.com
          from: GitHub Actions
          body: |
            New changes detected in phidata repository

            Commit Details:
            - Author: ${{ steps.latest.outputs.author }}
            - Date: ${{ steps.latest.outputs.date }}
            - Message: ${{ steps.latest.outputs.message }}
            - SHA: ${{ steps.latest.outputs.sha }}

            View commit: https://github.com/phidatahq/phidata/commit/${{ steps.latest.outputs.sha }}

      - name: Create issue for changes
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const files = JSON.parse(process.env.FILES);
            
            let fileChanges = files.map(file => 
              `- ${file.name} (${file.status}): +${file.additions} -${file.deletions}`
            ).join('\n');
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `📦 Phidata Repository Update Detected - ${new Date().toISOString().split('T')[0]}`,
              body: `# New changes detected in phidata repository

              ## Commit Details
              - **Author:** ${process.env.AUTHOR}
              - **Date:** ${process.env.DATE}
              - **Message:** ${process.env.MESSAGE}
              - **SHA:** ${process.env.SHA}
              
              ## Changed Files
              ${fileChanges}
              
              [View commit on GitHub](https://github.com/phidatahq/phidata/commit/${process.env.SHA})`
            });
        env:
          FILES: ${{ steps.latest.outputs.files }}
          AUTHOR: ${{ steps.latest.outputs.author }}
          DATE: ${{ steps.latest.outputs.date }}
          MESSAGE: ${{ steps.latest.outputs.message }}
          SHA: ${{ steps.latest.outputs.sha }}
