name: Monitor Phidata Repository

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest commit
        uses: actions/github-script@v6
        id: check
        with:
          script: |
            // Just get the latest commit info
            const { data: commit } = await github.rest.repos.getCommit({
              owner: 'phidatahq',
              repo: 'phidata',
              ref: 'main'
            });

            // Set outputs directly without any file operations
            core.setOutput('author', commit.commit.author.name);
            core.setOutput('date', commit.commit.author.date);
            core.setOutput('message', commit.commit.message);
            core.setOutput('sha', commit.sha);

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Phidata Repository Update
          to: alexanddanik@gmail.com
          from: GitHub Actions
          body: |
            Latest Phidata Repository Update

            Author: ${{ steps.check.outputs.author }}
            Date: ${{ steps.check.outputs.date }}
            Message: ${{ steps.check.outputs.message }}

            View commit: https://github.com/phidatahq/phidata/commit/${{ steps.check.outputs.sha }}
